#ifndef DEFINES_H
#define DEFINES_H

#ifndef LEAK_DETECTION
#define LEAK_DETECTION
#endif LEAK_DETECTION

#ifndef SAME_SYSTEM_NETWORK
#define SAME_SYSTEM_NETWORK

#define TEST_ON_LOOP_BACK

#endif SAME_SYSTEM_NETWORK

#endif DEFINES_H